int32 timestamp

#Robos amigos (x,y em mm)
uint8 idr1
float32 r1x
float32 r1y
uint8 idr2
float32 r2x
float32 r2y
uint8 idr3
float32 r3x
float32 r3y

#Robos adversarios (x,y em mm)
float32 ad1x
float32 ad1y
float32 ad2x
float32 ad2y
float32 ad3x
float32 ad3y
  
#Bola (x,y em mm)
float32 bx
float32 by

# Delimitacoes de campo (em mm)
float32 campoMinX
float32 campoMinY
float32 campoMaxX
float32 campoMaxY
float32 areaDefSup_X
float32 areaDefSup_Y
float32 areaDefInf_X
float32 areaDefInf_Y
float32 areaAtaSup_X
float32 areaAtaSup_Y
float32 areaAtaInf_X
float32 areaAtaInf_Y

#Gol amigo (x,y em mm)
float32 golDefSup_X
float32 golDefSup_Y
float32 golDefInf_X
float32 golDefInf_Y

#Gol adversario (x,y em mm)
float32 golAtaSup_X
float32 golAtaSup_Y
float32 golAtaInf_X
float32 golAtaInf_Y